steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']  # Replace 'build' with your build script if needed
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']  # Replace 'app' with your deployment command if needed
