steps:
  # Build the container image.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/smart-api-840b7', '.']

  # Push the container image to Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/smart-api-840b7']

  # Deploy the container image to Cloud Run.
  - name: 'gcloud'
    args: ['run', 'deploy', 'smart-api', '--image=gcr.io/smart-api-840b7', '--region=global']
