module.exports = {
  apps: [
    {
      name: 'smart-api',
      script: 'dist/server.js',
      instances: 1,
      exec_mode: 'fork',
      node_args: '--max-old-space-size=400',
      autorestart: true,
      exp_backoff_restart_delay: 100,
      watch: false,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/pm2-error.log',
      out_file: './logs/pm2-out.log',
      min_uptime: '10s',
      max_restarts: 10,
      kill_timeout: 10000,
      listen_timeout: 10000,
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'smart-api-feed',
      script: 'dist/marketFeedDaemon.js',
      instances: 1,
      exec_mode: 'fork',
      node_args: '--max-old-space-size=400',
      autorestart: true,
      exp_backoff_restart_delay: 100,
      restart_delay: 5000,
      watch: false,
      max_memory_restart: '512M',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: './logs/pm2-feed-error.log',
      out_file: './logs/pm2-feed-out.log',
      min_uptime: '10s',
      max_restarts: 10,
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
      },
      env_production: {
        NODE_ENV: 'production',
      },
    },
  ],
};
